### ISSUE TITLE
about Training models

### ISSUE THREAD

**Issue by WYan123** [ZackHodari/discrete_intonation#2]
Hello, what is this supposed to indicate?
![image](https://user-images.githubusercontent.com/51775884/102317924-63bda180-3fb3-11eb-9cc0-72fc874e5f62.png)
python f0_phrase_VAMP.py --experiment_name phrase_VAMP \
    --data_root ${DATA_DIR} \
    --train_dir train --train_id_list train_file_id_list.scp \
    --valid_dir valid --valid_id_list valid_file_id_list.scp \
    --test \
    --test_dir valid --test_id_list valid_1phrase_id_list.scp \

what means --test?

**Comment by ZackHodari** [comment]
This makes the experiment run on the provided test data. [Morgana](https://github.com/ZackHodari/morgana) allows you to specify different steps for validation and testing using [`analysis_for_XXX_batch`](https://zackhodari.github.io/morgana/reference/morgana.base_models.html#morgana.base_models.BaseModel.analysis_for_train_batch): e.g. calculate loss in validation, and run synthesis in testing.

There is also `--train` and `--valid` but these are `True` by default. Use `--no-train`, `--no-valid`, or `--no-test` if you want to ensure that stage is turned off.

You can always run `python f0_phrase_VAMP.py --help` for the model files in this repo, this will provide a description of all the arguments. This info is also available in [Morgana's documentation](https://zackhodari.github.io/morgana/), here is the [link for the ExperimentBuilder arguments](https://zackhodari.github.io/morgana/reference/command_line_arguments.html)

[Documentation for `test`](https://github.com/ZackHodari/morgana/blob/cb308638785284f0cd3c8799ca9dcaa018c741f9/morgana/experiment_builder.py#L105-L107): "If True, generation for --test_id_list will be performed after training"
